import { boolean, integer, jsonb, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
export const users = pgTable("users", { id: uuid("id").primaryKey().defaultRandom(), email: text("email").notNull().unique(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const agents = pgTable("agents", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").references(() => users.id), name: text("name").notNull(), tokenHash: text("token_hash").notNull(), lastSeenAt: timestamp("last_seen_at", { withTimezone: true }), version: text("version"), platform: text("platform"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });
/** An Android installation that can read the WiiM on its own local network. */
export const bridges = pgTable("bridges", { id: uuid("id").primaryKey().defaultRandom(), installationId: text("installation_id").notNull().unique(), viewerId: text("viewer_id"), name: text("name").notNull(), publicKey: text("public_key").notNull().unique(), lastSeenAt: timestamp("last_seen_at", { withTimezone: true }), enrolledAt: timestamp("enrolled_at", { withTimezone: true }).notNull().defaultNow(), revokedAt: timestamp("revoked_at", { withTimezone: true }) });
export const bridgeEnrollmentCodes = pgTable("bridge_enrollment_codes", { id: uuid("id").primaryKey().defaultRandom(), codeHash: text("code_hash").notNull().unique(), viewerId: text("viewer_id"), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), consumedAt: timestamp("consumed_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const bridgeNonces = pgTable("bridge_nonces", { id: uuid("id").primaryKey().defaultRandom(), bridgeId: uuid("bridge_id").notNull().references(() => bridges.id), nonce: text("nonce").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("bridge_nonce_unique").on(table.bridgeId, table.nonce)]);
export const devices = pgTable("devices", { id: text("id").primaryKey(), agentId: uuid("agent_id").references(() => agents.id), bridgeId: uuid("bridge_id").references(() => bridges.id), name: text("name").notNull(), deviceType: text("device_type").notNull().default("WiiM"), lastSeenAt: timestamp("last_seen_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });
export const artists = pgTable("artists", { id: uuid("id").primaryKey().defaultRandom(), name: text("name").notNull(), sortName: text("sort_name"), musicBrainzId: text("musicbrainz_id").unique(), discogsId: text("discogs_id"), wikidataId: text("wikidata_id"), wikipediaUrl: text("wikipedia_url"), biography: text("biography"), country: text("country"), metadataUpdatedAt: timestamp("metadata_updated_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });
export interface AlbumEditorial { heading: string; note: string; listeningCues: string[] }
export const albums = pgTable("albums", { id: uuid("id").primaryKey().defaultRandom(), artistId: uuid("artist_id").references(() => artists.id), title: text("title").notNull(), musicBrainzReleaseGroupId: text("musicbrainz_release_group_id").unique(), wikidataId: text("wikidata_id"), wikipediaUrl: text("wikipedia_url"), year: integer("year"), releaseDate: text("release_date"), genres: jsonb("genres").$type<string[]>(), tags: jsonb("tags").$type<string[]>(), description: text("description"), primaryArtworkUrl: text("primary_artwork_url"), editorial: jsonb("editorial").$type<AlbumEditorial>(), editorialModel: text("editorial_model"), editorialUpdatedAt: timestamp("editorial_updated_at", { withTimezone: true }), metadataUpdatedAt: timestamp("metadata_updated_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });
export const tracks = pgTable("tracks", { id: uuid("id").primaryKey().defaultRandom(), albumId: uuid("album_id").references(() => albums.id), title: text("title").notNull(), position: integer("position"), durationMs: integer("duration_ms"), musicBrainzId: text("musicbrainz_id") }, (table) => [uniqueIndex("tracks_album_musicbrainz_unique").on(table.albumId, table.musicBrainzId)]);
export const releases = pgTable("releases", { id: uuid("id").primaryKey().defaultRandom(), albumId: uuid("album_id").references(() => albums.id), discogsReleaseId: text("discogs_release_id"), musicBrainzReleaseId: text("musicbrainz_release_id"), title: text("title").notNull(), country: text("country"), year: integer("year"), label: text("label"), catalogNumber: text("catalog_number"), format: text("format"), formatDescription: text("format_description"), editionDescription: text("edition_description") }, (table) => [uniqueIndex("releases_discogs_release_unique").on(table.discogsReleaseId), uniqueIndex("releases_musicbrainz_release_unique").on(table.musicBrainzReleaseId)]);
export const credits = pgTable("credits", { id: uuid("id").primaryKey().defaultRandom(), albumId: uuid("album_id").references(() => albums.id), trackId: uuid("track_id").references(() => tracks.id), releaseId: uuid("release_id").references(() => releases.id), personName: text("person_name").notNull(), role: text("role").notNull(), source: text("source").notNull(), sourceId: text("source_id"), sourceUrl: text("source_url") });
export const artwork = pgTable("artwork", { id: uuid("id").primaryKey().defaultRandom(), albumId: uuid("album_id").references(() => albums.id), releaseId: uuid("release_id").references(() => releases.id), type: text("type").notNull(), url: text("url").notNull(), thumbnailUrl: text("thumbnail_url"), source: text("source").notNull(), sourceId: text("source_id"), width: integer("width"), height: integer("height") });
export const albumEnrichmentStates = pgTable("album_enrichment_states", { id: uuid("id").primaryKey().defaultRandom(), albumId: uuid("album_id").notNull().references(() => albums.id), source: text("source").notNull(), status: text("status").notNull(), error: text("error"), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() }, (table) => [uniqueIndex("album_enrichment_source_unique").on(table.albumId, table.source)]);
export const currentPlayback = pgTable("current_playback", { deviceId: text("device_id").primaryKey().references(() => devices.id), eventId: text("event_id").notNull().default(""), payload: jsonb("payload").notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });
export const listeningSessions = pgTable("listening_sessions", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").references(() => users.id), deviceId: text("device_id").references(() => devices.id), artistId: uuid("artist_id").references(() => artists.id), albumId: uuid("album_id").references(() => albums.id), trackId: uuid("track_id").references(() => tracks.id), source: text("source"), startedAt: timestamp("started_at", { withTimezone: true }).notNull(), endedAt: timestamp("ended_at", { withTimezone: true }), durationListenedMs: integer("duration_listened_ms") });
